In [1]:
import tensorflow as tf

In [2]:
tf.random.set_seed(777) # 시드를 설정합니다

In [3]:
import numpy as np
from tensorflow.keras.models import Sequential # 문법을 간단히 하기 위함, 층을 구성하겠다
from tensorflow.keras.layers import Dense      # 층을 구성하는 함수, 층에대한 노드갯수를 지정
from tensorflow.keras.optimizers import SGD    # 최적화 함수에 대하여 설정
from tensorflow.keras.losses import mse        # 로스 지정

In [20]:
# 데이터 준비하기(선형회귀)
data = np.array([[0,0], [1,0], [0,1], [1,1]]) # 입력 데이터셋의 형태는 신경망의 input값에 사용됨. 입력의 갯수와 신경망의 input의 갯수가 다르면 error
label = np.array([[0], [1], [1], [1]]) # y 값의 결과에 따라 다양한 활성화 함수가 사용됨.

np.shape(data)

(4, 2)

## 인공신경망 모델
- 배치사이즈 : 오차 계산하고 w,b값 갱신할 데이터 단위
- 현재 4개의 x값이 있으며 배치를 1로하면 1번째 데이터/ 4개의 모든 데이터중, 2/4, 3/4, 4/4 임
- 배치를 3으로하면 1(1,2,3데이터),/ 4,2(4번째데이터)/4 임
- 배치사이즈는 사용자가 정의하지 않아도 됨(optimizer에서 배치를 자동으로 결정함)
- epochs: 전체데이터에서 반복할 횟수

In [35]:

#모델구성하기
model = Sequential() # tensorflow.keras.models.Sequential()
model.add(Dense(2, input_shape = (2,), activation = 'linear')) # 활성화 함수 wx+b
model.add(Dense(1, activation = 'linear')) # 활성화 함수 wx+b
              # 층 2개, data[0,0]의 데이터 갯수 를의미, linear = wx+b

# 모델 준비하기
model.compile(optimizer=SGD(), loss = mse, metrics = ['acc']) # list 형태로 평가지표를 전달함

# 학습시키기
model.fit(data, label, epochs = 2, batch_size= 1)

Epoch 1/2
4/4 [==============================] - 0s 2ms/step - loss: 0.1324 - acc: 0.7500
Epoch 2/2
4/4 [==============================] - 0s 2ms/step - loss: 0.1266 - acc: 0.7500


In [36]:
model.summary()

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 2)                 6         
_________________________________________________________________
dense_13 (Dense)             (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [37]:
# Dense 층이 2개로 되어 층이 2개가 생김

model.get_weights()
# [w1-1, 1-2], [w2-1, 2-2], [b1, b2]

[array([[ 0.8200642 , -0.51085764],
        [ 0.01414693, -0.6049201 ]], dtype=float32),
 array([ 0.01296437, -0.00963994], dtype=float32),
 array([[ 0.7287892 ],
        [-0.55357766]], dtype=float32),
 array([0.01767095], dtype=float32)]

In [31]:

#모델구성하기
model = Sequential() # tensorflow.keras.models.Sequential()
model.add(Dense(1, input_shape = (2,), activation = 'linear')) # 활성화 함수 wx+b
            # 층 1개, data[0,0]의 데이터 갯수 를의미, linear = wx+b

# 모델 준비하기
model.compile(optimizer=SGD(), loss = mse, metrics = ['acc']) # list 형태로 평가지표를 전달함

# 학습시키기
model.fit(data, label, epochs = 10, batch_size= 1)

Epoch 1/10
4/4 [==============================] - 0s 3ms/step - loss: 0.2906 - acc: 0.7500
Epoch 2/10
4/4 [==============================] - 0s 2ms/step - loss: 0.2801 - acc: 0.7500
Epoch 3/10
4/4 [==============================] - 0s 2ms/step - loss: 0.2701 - acc: 0.7500
Epoch 4/10
4/4 [==============================] - 0s 2ms/step - loss: 0.2609 - acc: 0.7500
Epoch 5/10
4/4 [==============================] - 0s 2ms/step - loss: 0.2525 - acc: 0.7500
Epoch 6/10
4/4 [==============================] - 0s 3ms/step - loss: 0.2445 - acc: 0.7500
Epoch 7/10
4/4 [==============================] - 0s 2ms/step - loss: 0.2366 - acc: 0.7500
Epoch 8/10
4/4 [==============================] - 0s 3ms/step - loss: 0.2295 - acc: 0.7500
Epoch 9/10
4/4 [==============================] - 0s 2ms/step - loss: 0.2228 - acc: 0.7500
Epoch 10/10
4/4 [==============================] - 0s 3ms/step - loss: 0.2166 - acc: 0.7500


In [32]:
# x1과 x2의 자료를 가지고, x1의 w1, x2의 w2, b 한개
# model.get_weights() = [w1, w2], b

model.get_weights()

[array([[1.1371895 ],
        [0.11297257]], dtype=float32), array([0.06839774], dtype=float32)]

In [33]:
we = model.get_weights()
w1 = we[0][0] # x1의 w1
w2 = we[0][1] # x2의 w2
b = we[1]    # b

y_pred = data[:,0]*w1+data[:,1]*w2+b
y_pred

array([0.06839774, 1.20558725, 0.18137031, 1.31855982])

In [34]:
# Param y값을 계산하기 위한 노드의 갯수(x의 갯수 + 1 (b는 1* b 를 더해주기 때문))
# 현재 노드 x1, x2, b 항
# 여기에 계산되는 가중치가 Param의 갯수임(3 = w1, w2, b)
# w는 같은 배열에 넣고 [w1, w2]
# b는 한개의 항으로 제공 b
model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [26]:
# evaluate(): 평가를 진행합니다
model.evaluate(data, label)

# predict(): 예측을 합니다
preds = model.predict(data)
for a, b in zip(preds, label):
  print(f'예측값 {a} - 정답{b} ')


1/1 [==============================] - 0s 132ms/step - loss: 0.1575 - acc: 0.2500
예측값 [0.00581406 0.01011508] - 정답[0] 
예측값 [1.1174381 0.9463097] - 정답[1] 
예측값 [0.23556681 0.3083048 ] - 정답[1] 
예측값 [1.3471909 1.2444993] - 정답[1] 


In [27]:
# 위 내용은 정형 데이터셋에 사용되는 방법론임 
# 컴퓨터가 W와 b를 어떻게 인지하는지에 대해

## 활성화함수
Dense층의 결과를 계산하는 공식임

중간 Dense는 다음Dense에 넘어가기에 적합한 중간값 (대부분 Relu라는 함수를 사용함)(Relu : min = 0, max = 1)

최종 Dense는 원하는 y값을 의미함
- y값은 무한대의 숫자인 선형회귀이거나, 
> 결과는 무한대의 숫자중 1개 (활성화함수 기재안함)
- 0 또는 1값중 한개인 이항분류이거나, 
> 결과1은 0또는 1의 한개의 비트 (활성화함수 시그모이드)
> 결과2는 [1,0], [0,1]의 두개의 비트로 표현(활성화함수 소프트맥스)
- 여러개의 다항분류이거나, 무조건 분류갯수만큼 원핫인코딩함
> ex) 개, 고양이, 사자, 사슴 4개의 분류가있으면 개는 1, 고양이 2, 사자는 3, 사슴은 4, 개[1,0,0,0], 고양이는 [0,1,0,0] 과 같이 표현(활성화함수 소프트맥스)