# 경사하강법
- 기울기 소실, 그라디언트 소실 문제

In [22]:
# 선형회귀 뉴런

class Neuron:
    
    def __init__(self):
        self.w = 1.0     # 가중치를 초기화합니다
        self.b = 1.0     # 절편을 초기화합니다
    
    def forpass(self, x):
        y_hat = x * self.w + self.b       # 직선 방정식을 계산합니다
        return y_hat
    
    def backprop(self, x, err):
        w_grad = x * err    # 가중치에 대한 그래디언트를 계산합니다
        b_grad = 1 * err    # 절편에 대한 그래디언트를 계산합니다
        return w_grad, b_grad

    def fit(self, x, y, epochs=100):
        for i in range(epochs):           # 에포크만큼 반복합니다
            for x_i, y_i in zip(x, y):    # 모든 샘플에 대해 반복합니다, 배치 1 자료임
                y_hat = self.forpass(x_i) # 정방향 계산

                err = -(y_i - y_hat)      # 오차 계산

                w_grad, b_grad = self.backprop(x_i, err)  # 역방향 계산
                self.w -= w_grad          # 가중치 업데이트
                self.b -= b_grad          # 절편 업데이트
            print(self.w, self.b)
            print(y_i, y_hat)
            print('-------------------------------')

In [23]:
import numpy as np

x=np.array([20,10,20,10,100,20,4,2])
y=np.array([200,5,100,20,30,40,5,1])

neuron = Neuron()
neuron.fit(x, y)

-3.044490607004028e+18 -1.726732813004091e+18
1 1.9539285067530368e+18
-------------------------------
-1.062089077986025e+36 -6.023812512584651e+35
1 6.816398518076288e+35
-------------------------------
-3.7051623906544444e+53 -2.101443657843168e+53
1 2.3779421097880142e+53
-------------------------------
-1.292568450769889e+71 -7.33101410089283e+70
1 8.295595779072652e+70
-------------------------------
-4.5092037103144836e+88 -2.5574688879667512e+88
1 2.8939690771489294e+88
-------------------------------
-1.573063158783047e+106 -8.921885871316658e+105
1 1.00957872617444e+106
-------------------------------
-5.487726571013394e+123 -3.1124541876278203e+123
1 3.521976832413652e+123
-------------------------------
-1.9144268143374556e+141 -1.0857985867344807e+141
1 1.228663053852348e+141
-------------------------------
-6.678594459886605e+158 -3.787874454959117e+158
1 4.286265843683082e+158
-------------------------------
-2.3298683253694645e+176 -1.3214230578143556e+176
1 1.495289927

<ipython-input-22-de5e106e0728>:14: RuntimeWarning: overflow encountered in multiply
  w_grad = x * err    # 가중치에 대한 그래디언트를 계산합니다
<ipython-input-22-de5e106e0728>:26: RuntimeWarning: invalid value encountered in double_scalars
  self.w -= w_grad          # 가중치 업데이트


In [15]:
w=1;b=1
y_hat = x * w + b       # 직선 방정식을 계산합니다
print('\n-------예측값')
print(y_hat) #정방향 계산
err = -(y - y_hat)

print('\n-------err: 예측값-실제값')
print(err)

w_grad = x * err    # 가중치에 대한 그래디언트를 계산합니다
b_grad = 1 * err

w -= w_grad
b -= b_grad


print('\n-------w갱신, b갱신')
print(w, b)


-------예측값
[ 21  11  21  11 101  21   5   3]

-------err: 예측값-실제값
[-179    6  -79   -9   71  -19    0    2]

-------w갱신, b갱신
[ 3581   -59  1581    91 -7099   381     1    -3] [180  -5  80  10 -70  20   1  -1]


# 찾아서 공부할 것

1. 그라디언트 소실 gradient vanishing : 기울기가 너무 작아짐
2. 그라디언트 폭주 gradient exploding : 기울기가 너무 커짐
3. 그라디언트 클리핑 gradient clipping : 최적화 함수 사용시 그라디언트 임계값을 설정함
4. 배치 정규화 : 배치사이즈를 받아서 그 자료를 정규화(평균을 0으로 만듬)

https://codetorial.net/tensorflow/basics_of_optimizer.html